export const GAME_DATA: Record<string, any[]> = {
  suku_kata_kv: [
    { type: 'dengar', audio: 'ba', options: ['fo', 'no', 'ba', 'ko'], answer: 'ba' },
    { type: 'dengar', audio: 'be', options: ['ha', 'be', 'pa', 'fa'], answer: 'be' },
    { type: 'dengar', audio: 'bi', options: ['ci', 'bi', 'bo', 'no'], answer: 'bi' },
    { type: 'dengar', audio: 'bo', options: ['mu', 'bo', 'li', 'le'], answer: 'bo' },
    { type: 'dengar', audio: 'bu', options: ['bu', 'na', 'lu', 'pe'], answer: 'bu' },
    { type: 'dengar', audio: 'ca', options: ['mi', 'ca', 'cu', 'pa'], answer: 'ca' },
    { type: 'dengar', audio: 'ce', options: ['be', 'la', 'jo', 'ce'], answer: 'ce' },
    { type: 'dengar', audio: 'ci', options: ['ha', 'la', 'ba', 'ci'], answer: 'ci' },
    { type: 'dengar', audio: 'co', options: ['ji', 'co', 'ku', 'me'], answer: 'co' },
    { type: 'dengar', audio: 'cu', options: ['cu', 'do', 'ce', 'ke'], answer: 'cu' },
    { type: 'dengar', audio: 'da', options: ['bi', 'li', 'da', 'be'], answer: 'da' },
    { type: 'dengar', audio: 'de', options: ['ke', 'ni', 'bu', 'de'], answer: 'de' },
    { type: 'dengar', audio: 'di', options: ['go', 'di', 'co', 'ku'], answer: 'di' },
    { type: 'dengar', audio: 'do', options: ['na', 'go', 'do', 'li'], answer: 'do' },
    { type: 'dengar', audio: 'du', options: ['ju', 'ke', 'du', 'hi'], answer: 'du' },
    { type: 'dengar', audio: 'fa', options: ['ko', 'fa', 'me', 'li'], answer: 'fa' },
    { type: 'dengar', audio: 'fe', options: ['ku', 'bo', 'fe', 'ha'], answer: 'fe' },
    { type: 'dengar', audio: 'fi', options: ['ju', 'ha', 'mu', 'fi'], answer: 'fi' },
    { type: 'dengar', audio: 'fo', options: ['fo', 'nu', 'gu', 'ma'], answer: 'fo' },
    { type: 'dengar', audio: 'fu', options: ['je', 'pi', 'he', 'fu'], answer: 'fu' },
    { type: 'dengar', audio: 'ga', options: ['lo', 'he', 'ga', 'ho'], answer: 'ga' },
    { type: 'dengar', audio: 'ge', options: ['pa', 'nu', 'ku', 'ge'], answer: 'ge' },
    { type: 'dengar', audio: 'gi', options: ['hu', 'du', 'ba', 'gi'], answer: 'gi' },
    { type: 'dengar', audio: 'go', options: ['da', 'pi', 'hu', 'go'], answer: 'go' },
    { type: 'dengar', audio: 'gu', options: ['ja', 'bu', 'gu', 'be'], answer: 'gu' },
    { type: 'dengar', audio: 'ha', options: ['ni', 'pu', 'ha', 'me'], answer: 'ha' },
    { type: 'dengar', audio: 'he', options: ['ke', 'he', 'fo', 'no'], answer: 'he' },
    { type: 'dengar', audio: 'hi', options: ['gi', 'hi', 'ni', 'fo'], answer: 'hi' },
    { type: 'dengar', audio: 'ho', options: ['ha', 'mi', 'nu', 'ho'], answer: 'ho' },
    { type: 'dengar', audio: 'hu', options: ['jo', 'po', 'hu', 'pu'], answer: 'hu' },
    { type: 'dengar', audio: 'ja', options: ['ja', 'fa', 'ba', 'di'], answer: 'ja' },
    { type: 'dengar', audio: 'je', options: ['do', 'fu', 'je', 'ku'], answer: 'je' },
    { type: 'dengar', audio: 'ji', options: ['ki', 'du', 'ji', 'ho'], answer: 'ji' },
    { type: 'dengar', audio: 'jo', options: ['pe', 'jo', 'ma', 'du'], answer: 'jo' },
    { type: 'dengar', audio: 'ju', options: ['do', 'du', 'hu', 'ju'], answer: 'ju' },
    { type: 'dengar', audio: 'ka', options: ['mo', 'ka', 'bi', 'hi'], answer: 'ka' },
    { type: 'dengar', audio: 'ke', options: ['fu', 'ke', 'da', 'mi'], answer: 'ke' },
    { type: 'dengar', audio: 'ki', options: ['fo', 'ki', 'go', 'he'], answer: 'ki' },
    { type: 'dengar', audio: 'ko', options: ['mi', 'ko', 'po', 'gi'], answer: 'ko' },
    { type: 'dengar', audio: 'ku', options: ['de', 'ku', 'ke', 'me'], answer: 'ku' },
    { type: 'dengar', audio: 'la', options: ['je', 'no', 'be', 'la'], answer: 'la' },
    { type: 'dengar', audio: 'le', options: ['ku', 'mi', 'le', 'bu'], answer: 'le' },
    { type: 'dengar', audio: 'li', options: ['bi', 'nu', 'li', 'fa'], answer: 'li' },
    { type: 'dengar', audio: 'lo', options: ['ce', 'lo', 'ji', 'da'], answer: 'lo' },
    { type: 'dengar', audio: 'lu', options: ['mo', 'ni', 'ko', 'lu'], answer: 'lu' },
    { type: 'dengar', audio: 'ma', options: ['ma', 'po', 'bo', 'ha'], answer: 'ma' },
    { type: 'dengar', audio: 'me', options: ['me', 'da', 'ka', 'ki'], answer: 'me' },
    { type: 'dengar', audio: 'mi', options: ['he', 'hi', 'nu', 'mi'], answer: 'mi' },
    { type: 'dengar', audio: 'mo', options: ['mu', 'di', 'ki', 'mo'], answer: 'mo' },
    { type: 'dengar', audio: 'mu', options: ['mu', 'ha', 'be', 'le'], answer: 'mu' },
    { type: 'dengar', audio: 'na', options: ['no', 'me', 'ci', 'na'], answer: 'na' },
    { type: 'dengar', audio: 'ne', options: ['ne', 'de', 'di', 'ma'], answer: 'ne' },
    { type: 'dengar', audio: 'ni', options: ['de', 'bu', 'ni', 'nu'], answer: 'ni' },
    { type: 'dengar', audio: 'no', options: ['ki', 'no', 'je', 'pi'], answer: 'no' },
    { type: 'dengar', audio: 'nu', options: ['fi', 'me', 'nu', 'ju'], answer: 'nu' },
    { type: 'dengar', audio: 'pa', options: ['ma', 'ni', 'gu', 'pa'], answer: 'pa' },
    { type: 'dengar', audio: 'pe', options: ['pe', 'du', 'ki', 'bi'], answer: 'pe' },
    { type: 'dengar', audio: 'pi', options: ['pi', 'bu', 'pa', 'hu'], answer: 'pi' },
    { type: 'dengar', audio: 'po', options: ['ju', 'po', 'ci', 'ke'], answer: 'po' },
    { type: 'dengar', audio: 'pu', options: ['fu', 'be', 'du', 'pu'], answer: 'pu' },
  ],
  suku_kata_kv_kv: [
    { type: 'padan', image: '🛺', imageText: 'beca', options: ['mata', 'sudu', 'beca', 'tebu'], answer: 'beca' },
    { type: 'padan', image: '🥔', imageText: 'ciku', options: ['ciku', 'rusa', 'kuku', 'lidi'], answer: 'ciku' },
    { type: 'padan', image: '👉', imageText: 'jari', options: ['raga', 'paku', 'labu', 'jari'], answer: 'jari' },
    { type: 'padan', image: '💅', imageText: 'kuku', options: ['jari', 'kuku', 'mata', 'sudu'], answer: 'kuku' },
    { type: 'padan', image: '🎃', imageText: 'labu', options: ['jari', 'ciku', 'labu', 'lidi'], answer: 'labu' },
    { type: 'padan', image: '🪵', imageText: 'lidi', options: ['sawi', 'tebu', 'lidi', 'raga'], answer: 'lidi' },
    { type: 'padan', image: '👁️', imageText: 'mata', options: ['jari', 'mata', 'raga', 'kuku'], answer: 'mata' },
    { type: 'padan', image: '🍚', imageText: 'nasi', options: ['tebu', 'nasi', 'mata', 'labu'], answer: 'nasi' },
    { type: 'padan', image: '📌', imageText: 'paku', options: ['jari', 'mata', 'paku', 'tebu'], answer: 'paku' },
    { type: 'padan', image: '🧺', imageText: 'raga', options: ['raga', 'beca', 'labu', 'rusa'], answer: 'raga' },
    { type: 'padan', image: '🦌', imageText: 'rusa', options: ['rusa', 'beca', 'nasi', 'lidi'], answer: 'rusa' },
    { type: 'padan', image: '🥬', imageText: 'sawi', options: ['sudu', 'sawi', 'nasi', 'rusa'], answer: 'sawi' },
    { type: 'padan', image: '🥄', imageText: 'sudu', options: ['tebu', 'sudu', 'mata', 'paku'], answer: 'sudu' },
    { type: 'padan', image: '🪢', imageText: 'tali', options: ['tali', 'tebu', 'labu', 'sudu'], answer: 'tali' },
    { type: 'padan', image: '🎋', imageText: 'tebu', options: ['raga', 'tebu', 'jari', 'mata'], answer: 'tebu' },
  ],
  suku_kata_v_kv: [
    { type: 'lengkap', image: '🔨', imageText: 'alu', prefix: '___', suffix: 'lu', options: ['i', 'e', 'o', 'a'], answer: 'a' },
    { type: 'lengkap', image: '🔥', imageText: 'api', prefix: '___', suffix: 'pi', options: ['e', 'a', 'u', 'o'], answer: 'a' },
    { type: 'lengkap', image: '👩', imageText: 'ibu', prefix: '___', suffix: 'bu', options: ['u', 'i', 'o', 'e'], answer: 'i' },
    { type: 'lengkap', image: '🥩', imageText: 'isi', prefix: '___', suffix: 'si', options: ['o', 'i', 'u', 'e'], answer: 'i' },
    { type: 'lengkap', image: '🥔', imageText: 'ubi', prefix: '___', suffix: 'bi', options: ['i', 'u', 'o', 'a'], answer: 'u' },
    { type: 'lengkap', image: '⛰️', imageText: 'ulu', prefix: '___', suffix: 'lu', options: ['u', 'a', 'o', 'e'], answer: 'u' },
  ],
  suku_kata_kv_kv_kv: [
    { type: 'susun', image: '🐸', imageText: 'berudu', syllables: ['be', 'ru', 'du'], options: ['du', 'be', 'ru'] },
    { type: 'susun', image: '🍠', imageText: 'keladi', syllables: ['ke', 'la', 'di'], options: ['ke', 'di', 'la'] },
    { type: 'susun', image: '🥥', imageText: 'kelapa', syllables: ['ke', 'la', 'pa'], options: ['la', 'pa', 'ke'] },
    { type: 'susun', image: '👕', imageText: 'kemeja', syllables: ['ke', 'me', 'ja'], options: ['me', 'ja', 'ke'] },
    { type: 'susun', image: '🚗', imageText: 'kereta', syllables: ['ke', 're', 'ta'], options: ['re', 'ta', 'ke'] },
    { type: 'susun', image: '🪑', imageText: 'kerusi', syllables: ['ke', 'ru', 'si'], options: ['ke', 'si', 'ru'] },
    { type: 'susun', image: '🪔', imageText: 'pelita', syllables: ['pe', 'li', 'ta'], options: ['pe', 'li', 'ta'] },
    { type: 'susun', image: '🕳️', imageText: 'perigi', syllables: ['pe', 'ri', 'gi'], options: ['gi', 'pe', 'ri'] },
    { type: 'susun', image: '👨‍🌾', imageText: 'petani', syllables: ['pe', 'ta', 'ni'], options: ['ni', 'pe', 'ta'] },
    { type: 'susun', image: '🥒', imageText: 'petola', syllables: ['pe', 'to', 'la'], options: ['la', 'pe', 'to'] },
    { type: 'susun', image: '🌱', imageText: 'semalu', syllables: ['se', 'ma', 'lu'], options: ['lu', 'ma', 'se'] },
    { type: 'susun', image: '👞', imageText: 'sepatu', syllables: ['se', 'pa', 'tu'], options: ['se', 'pa', 'tu'] },
    { type: 'susun', image: '🍅', imageText: 'tomato', syllables: ['to', 'ma', 'to'], options: ['ma', 'to', 'to'] },
    { type: 'susun', image: '👩', imageText: 'wanita', syllables: ['wa', 'ni', 'ta'], options: ['ta', 'ni', 'wa'] },
  ],
  suku_kata_kvk: [
    { type: 'teka', image: '🚌', imageText: 'bas', text: 'b_s', options: ['u', 'a', 'i', 'e'], answer: 'a' },
    { type: 'teka', image: '🎒', imageText: 'beg', text: 'b_g', options: ['a', 'e', 'i', 'o'], answer: 'e' },
    { type: 'teka', image: '🚤', imageText: 'bot', text: 'b_t', options: ['o', 'u', 'a', 'i'], answer: 'o' },
    { type: 'teka', image: '🎨', imageText: 'cat', text: 'c_t', options: ['a', 'i', 'e', 'u'], answer: 'a' },
    { type: 'teka', image: '🥛', imageText: 'jag', text: 'j_g', options: ['o', 'a', 'u', 'i'], answer: 'a' },
    { type: 'teka', image: '⏰', imageText: 'jam', text: 'j_m', options: ['o', 'e', 'a', 'u'], answer: 'a' },
    { type: 'teka', image: '🍯', imageText: 'jem', text: 'j_m', options: ['o', 'i', 'e', 'u'], answer: 'e' },
    { type: 'teka', image: '✈️', imageText: 'jet', text: 'j_t', options: ['a', 'u', 'e', 'o'], answer: 'e' },
    { type: 'teka', image: '🍰', imageText: 'kek', text: 'k_k', options: ['e', 'u', 'i', 'a'], answer: 'e' },
    { type: 'teka', image: '🧥', imageText: 'kot', text: 'k_t', options: ['i', 'e', 'a', 'o'], answer: 'o' },
    { type: 'teka', image: '⛽', imageText: 'pam', text: 'p_m', options: ['e', 'a', 'i', 'u'], answer: 'a' },
    { type: 'teka', image: '🖊️', imageText: 'pen', text: 'p_n', options: ['o', 'e', 'i', 'u'], answer: 'e' },
    { type: 'teka', image: '💊', imageText: 'pil', text: 'p_l', options: ['u', 'i', 'e', 'a'], answer: 'i' },
    { type: 'teka', image: '📌', imageText: 'pin', text: 'p_n', options: ['u', 'o', 'e', 'i'], answer: 'i' },
    { type: 'teka', image: '🪜', imageText: 'rak', text: 'r_k', options: ['a', 'u', 'i', 'e'], answer: 'a' },
    { type: 'teka', image: '🛞', imageText: 'rim', text: 'r_m', options: ['e', 'i', 'o', 'a'], answer: 'i' },
    { type: 'teka', image: '🌹', imageText: 'ros', text: 'r_s', options: ['a', 'u', 'e', 'o'], answer: 'o' },
    { type: 'teka', image: '🍲', imageText: 'sup', text: 's_p', options: ['i', 'e', 'o', 'u'], answer: 'u' },
    { type: 'teka', image: '🥫', imageText: 'tin', text: 't_n', options: ['i', 'a', 'o', 'u'], answer: 'i' },
    { type: 'teka', image: '🚐', imageText: 'van', text: 'v_n', options: ['e', 'a', 'o', 'i'], answer: 'a' },
  ],
  suku_kata_v_kvk: [
    { type: 'bakul', words: [{ id: 1, text: 'ayam', image: '🐔', category: 'a' }] },
    { type: 'bakul', words: [{ id: 2, text: 'enam', image: '6️⃣', category: 'b' }] },
    { type: 'bakul', words: [{ id: 3, text: 'epal', image: '🍎', category: 'a' }] },
    { type: 'bakul', words: [{ id: 4, text: 'ikan', image: '🐟', category: 'b' }] },
    { type: 'bakul', words: [{ id: 5, text: 'itik', image: '🦆', category: 'a' }] },
    { type: 'bakul', words: [{ id: 6, text: 'obor', image: '🔥', category: 'b' }] },
    { type: 'bakul', words: [{ id: 7, text: 'oren', image: '🍊', category: 'a' }] },
    { type: 'bakul', words: [{ id: 8, text: 'otak', image: '🧠', category: 'b' }] },
    { type: 'bakul', words: [{ id: 9, text: 'ular', image: '🐍', category: 'a' }] },
    { type: 'bakul', words: [{ id: 10, text: 'ulat', image: '🐛', category: 'b' }] },
  ],
  suku_kata_kv_kvk: [
    { type: 'dengar', audio: 'bakul', options: ['kicap', 'kapal', 'betik', 'bakul'], answer: 'bakul' },
    { type: 'dengar', audio: 'belon', options: ['botol', 'ketam', 'belon', 'beruk'], answer: 'belon' },
    { type: 'dengar', audio: 'beruk', options: ['sikat', 'beruk', 'bakul', 'ketam'], answer: 'beruk' },
    { type: 'dengar', audio: 'betik', options: ['betik', 'kapak', 'cawan', 'gitar'], answer: 'betik' },
    { type: 'dengar', audio: 'botol', options: ['pagar', 'botol', 'kipas', 'sikat'], answer: 'botol' },
    { type: 'dengar', audio: 'cawan', options: ['botol', 'cawan', 'bakul', 'gajah'], answer: 'cawan' },
    { type: 'dengar', audio: 'cerek', options: ['pagar', 'sikat', 'cerek', 'belon'], answer: 'cerek' },
    { type: 'dengar', audio: 'gajah', options: ['gitar', 'kapak', 'gajah', 'kipas'], answer: 'gajah' },
    { type: 'dengar', audio: 'gelas', options: ['cerek', 'gajah', 'gelas', 'makan'], answer: 'gelas' },
    { type: 'dengar', audio: 'gitar', options: ['beruk', 'nanas', 'betik', 'gitar'], answer: 'gitar' },
    { type: 'dengar', audio: 'kapak', options: ['bakul', 'gitar', 'cerek', 'kapak'], answer: 'kapak' },
    { type: 'dengar', audio: 'kapal', options: ['kasut', 'kapal', 'ketam', 'gelas'], answer: 'kapal' },
    { type: 'dengar', audio: 'kasut', options: ['sikat', 'kasut', 'botol', 'kipas'], answer: 'kasut' },
    { type: 'dengar', audio: 'katil', options: ['gitar', 'nanas', 'bakul', 'katil'], answer: 'katil' },
    { type: 'dengar', audio: 'ketam', options: ['ketam', 'marah', 'kapal', 'sabun'], answer: 'ketam' },
    { type: 'dengar', audio: 'kicap', options: ['ketam', 'sikat', 'sabun', 'kicap'], answer: 'kicap' },
    { type: 'dengar', audio: 'kilat', options: ['kilat', 'gajah', 'sabun', 'cerek'], answer: 'kilat' },
    { type: 'dengar', audio: 'kipas', options: ['kipas', 'kasut', 'cerek', 'marah'], answer: 'kipas' },
    { type: 'dengar', audio: 'lilin', options: ['nanas', 'marah', 'lilin', 'kipas'], answer: 'lilin' },
    { type: 'dengar', audio: 'makan', options: ['makan', 'kicap', 'belon', 'cawan'], answer: 'makan' },
    { type: 'dengar', audio: 'marah', options: ['katil', 'sikat', 'gelas', 'marah'], answer: 'marah' },
    { type: 'dengar', audio: 'nanas', options: ['kapak', 'beruk', 'nanas', 'gelas'], answer: 'nanas' },
    { type: 'dengar', audio: 'pagar', options: ['kapal', 'nanas', 'kipas', 'pagar'], answer: 'pagar' },
    { type: 'dengar', audio: 'sabun', options: ['botol', 'katil', 'pagar', 'sabun'], answer: 'sabun' },
    { type: 'dengar', audio: 'sikat', options: ['gelas', 'beruk', 'sikat', 'kapal'], answer: 'sikat' },
    { type: 'dengar', audio: 'tayar', options: ['tayar', 'marah', 'botol', 'gitar'], answer: 'tayar' },
  ],
  suku_kata_kvk_kv: [
    { type: 'padan', image: '🪣', imageText: 'baldi', options: ['baldi', 'garpu', 'kunci', 'lampu'], answer: 'baldi' },
    { type: 'padan', image: '🥬', imageText: 'bendi', options: ['jambu', 'lembu', 'lampu', 'bendi'], answer: 'bendi' },
    { type: 'padan', image: '🍴', imageText: 'garpu', options: ['kunci', 'jambu', 'bendi', 'garpu'], answer: 'garpu' },
    { type: 'padan', image: '🍐', imageText: 'jambu', options: ['garpu', 'jambu', 'bendi', 'lampu'], answer: 'jambu' },
    { type: 'padan', image: '🔑', imageText: 'kunci', options: ['jambu', 'bendi', 'kunci', 'pintu'], answer: 'kunci' },
    { type: 'padan', image: '💡', imageText: 'lampu', options: ['bendi', 'lampu', 'jambu', 'pintu'], answer: 'lampu' },
    { type: 'padan', image: '🐄', imageText: 'lembu', options: ['bendi', 'kunci', 'lembu', 'jambu'], answer: 'lembu' },
    { type: 'padan', image: '🚪', imageText: 'pintu', options: ['jambu', 'pintu', 'lembu', 'bendi'], answer: 'pintu' },
  ],
  suku_kata_kvk_kvk: [
    { type: 'lengkap', image: '🍪', imageText: 'biskut', prefix: 'bis', suffix: '___', options: ['cin', 'kut', 'but', 'put'], answer: 'kut' },
    { type: 'lengkap', image: '🪞', imageText: 'cermin', prefix: 'cer', suffix: '___', options: ['min', 'pah', 'tor', 'bol'], answer: 'min' },
    { type: 'lengkap', image: '💍', imageText: 'cincin', prefix: 'cin', suffix: '___', options: ['cis', 'tor', 'cin', 'duk'], answer: 'cin' },
    { type: 'lengkap', image: '👨‍⚕️', imageText: 'doktor', prefix: 'dok', suffix: '___', options: ['tor', 'bol', 'jid', 'duk'], answer: 'tor' },
    { type: 'lengkap', image: '🔥', imageText: 'mancis', prefix: 'man', suffix: '___', options: ['pah', 'cis', 'but', 'cin'], answer: 'cis' },
    { type: 'lengkap', image: '🕌', imageText: 'masjid', prefix: 'mas', suffix: '___', options: ['min', 'jid', 'cin', 'cis'], answer: 'jid' },
    { type: 'lengkap', image: '💇', imageText: 'rambut', prefix: 'ram', suffix: '___', options: ['duk', 'pan', 'but', 'kut'], answer: 'but' },
    { type: 'lengkap', image: '🌿', imageText: 'rumput', prefix: 'rum', suffix: '___', options: ['put', 'cin', 'pah', 'jid'], answer: 'put' },
    { type: 'lengkap', image: '🗑️', imageText: 'sampah', prefix: 'sam', suffix: '___', options: ['pah', 'duk', 'cin', 'kut'], answer: 'pah' },
    { type: 'lengkap', image: '🛶', imageText: 'sampan', prefix: 'sam', suffix: '___', options: ['min', 'bol', 'pan', 'kut'], answer: 'pan' },
    { type: 'lengkap', image: '🦌', imageText: 'tanduk', prefix: 'tan', suffix: '___', options: ['jid', 'but', 'bol', 'duk'], answer: 'duk' },
    { type: 'lengkap', image: '🚪', imageText: 'tombol', prefix: 'tom', suffix: '___', options: ['duk', 'put', 'bol', 'pah'], answer: 'bol' },
  ],
  suku_kata_kvkk: [
    { type: 'teka', image: '🏦', imageText: 'bank', text: 'b_nk', options: ['e', 'o', 'i', 'a'], answer: 'a' },
    { type: 'teka', image: '🪘', imageText: 'gong', text: 'g_ng', options: ['u', 'i', 'a', 'o'], answer: 'o' },
    { type: 'teka', image: '⛵', imageText: 'jong', text: 'j_ng', options: ['i', 'e', 'u', 'o'], answer: 'o' },
    { type: 'teka', image: '🛢️', imageText: 'tong', text: 't_ng', options: ['i', 'a', 'o', 'e'], answer: 'o' },
    { type: 'teka', image: '💵', imageText: 'wang', text: 'w_ng', options: ['o', 'e', 'i', 'a'], answer: 'a' },
    { type: 'teka', image: '🏗️', imageText: 'zink', text: 'z_nk', options: ['a', 'u', 'e', 'i'], answer: 'i' },
  ],
  suku_kata_kv_kv_kvk: [
    { type: 'susun', image: '🚲', imageText: 'basikal', syllables: ['ba', 'si', 'kal'], options: ['ba', 'si', 'kal'] },
    { type: 'susun', image: '🦇', imageText: 'kelawar', syllables: ['ke', 'la', 'war'], options: ['ke', 'war', 'la'] },
    { type: 'susun', image: '🍠', imageText: 'keledek', syllables: ['ke', 'le', 'dek'], options: ['le', 'dek', 'ke'] },
    { type: 'susun', image: '🍙', imageText: 'ketupat', syllables: ['ke', 'tu', 'pat'], options: ['tu', 'pat', 'ke'] },
    { type: 'susun', image: '🔺', imageText: 'piramid', syllables: ['pi', 'ra', 'mid'], options: ['ra', 'pi', 'mid'] },
    { type: 'susun', image: '🌰', imageText: 'pulasan', syllables: ['pu', 'la', 'san'], options: ['la', 'san', 'pu'] },
    { type: 'susun', image: '☎️', imageText: 'telefon', syllables: ['te', 'le', 'fon'], options: ['fon', 'le', 'te'] },
    { type: 'susun', image: '🖱️', imageText: 'tetikus', syllables: ['te', 'ti', 'kus'], options: ['te', 'kus', 'ti'] },
    { type: 'susun', image: '🦒', imageText: 'zirafah', syllables: ['zi', 'ra', 'fah'], options: ['fah', 'ra', 'zi'] },
  ],
  suku_kata_kvk_kv_kvk: [
    { type: 'susun', image: '🍈', imageText: 'cempedak', syllables: ['cem', 'pe', 'dak'], options: ['cem', 'pe', 'dak'] },
    { type: 'susun', image: '🍄', imageText: 'cendawan', syllables: ['cen', 'da', 'wan'], options: ['da', 'wan', 'cen'] },
    { type: 'susun', image: '🌉', imageText: 'jambatan', syllables: ['jam', 'ba', 'tan'], options: ['jam', 'ba', 'tan'] },
    { type: 'susun', image: '💻', imageText: 'komputer', syllables: ['kom', 'pu', 'ter'], options: ['ter', 'kom', 'pu'] },
    { type: 'susun', image: '📏', imageText: 'pembaris', syllables: ['pem', 'ba', 'ris'], options: ['ris', 'ba', 'pem'] },
    { type: 'susun', image: '🏺', imageText: 'tempayan', syllables: ['tem', 'pa', 'yan'], options: ['tem', 'yan', 'pa'] },
  ],

  huruf_konsonan: [
    { type: 'teka', image: '📖', imageText: 'buku', text: 'b _ k u', options: ['u', 'a', 'i', 'e'], answer: 'u' }
  ],
  fonik_abc: [
    { type: 'dengar', audio: 'a', options: ['a', 'b', 'c', 'd'], answer: 'a' }
  ],
  cerita_pendek: [
    { type: 'bakul', bakulATitle: 'betul', bakulADesc: 'ayat logik', bakulBTitle: 'salah', bakulBDesc: 'ayat pelik', words: [{ id: 1, text: 'Ikan terbang di awan.', image: '🐟', category: 'b' }] }
  ]
};
