const ASAS_SHELVES_DATA = [
    {
        id: 'KV', title: 'Rak 1 — KV', color: '#ec4899',
        words: [
            { syl: ['ba'], word: 'ba', emoji: '🔊' },
            { syl: ['be'], word: 'be', emoji: '🔊' },
            { syl: ['bi'], word: 'bi', emoji: '🔊' },
            { syl: ['bo'], word: 'bo', emoji: '🔊' },
            { syl: ['bu'], word: 'bu', emoji: '🔊' },
            { syl: ['ca'], word: 'ca', emoji: '🔊' },
            { syl: ['ce'], word: 'ce', emoji: '🔊' },
            { syl: ['ci'], word: 'ci', emoji: '🔊' },
            { syl: ['co'], word: 'co', emoji: '🔊' },
            { syl: ['cu'], word: 'cu', emoji: '🔊' },
            { syl: ['da'], word: 'da', emoji: '🔊' },
            { syl: ['de'], word: 'de', emoji: '🔊' },
            { syl: ['di'], word: 'di', emoji: '🔊' },
            { syl: ['do'], word: 'do', emoji: '🔊' },
            { syl: ['du'], word: 'du', emoji: '🔊' },
            { syl: ['fa'], word: 'fa', emoji: '🔊' },
            { syl: ['fe'], word: 'fe', emoji: '🔊' },
            { syl: ['fi'], word: 'fi', emoji: '🔊' },
            { syl: ['fo'], word: 'fo', emoji: '🔊' },
            { syl: ['fu'], word: 'fu', emoji: '🔊' },
            { syl: ['ga'], word: 'ga', emoji: '🔊' },
            { syl: ['ge'], word: 'ge', emoji: '🔊' },
            { syl: ['gi'], word: 'gi', emoji: '🔊' },
            { syl: ['go'], word: 'go', emoji: '🔊' },
            { syl: ['gu'], word: 'gu', emoji: '🔊' },
            { syl: ['ha'], word: 'ha', emoji: '🔊' },
            { syl: ['he'], word: 'he', emoji: '🔊' },
            { syl: ['hi'], word: 'hi', emoji: '🔊' },
            { syl: ['ho'], word: 'ho', emoji: '🔊' },
            { syl: ['hu'], word: 'hu', emoji: '🔊' },
            { syl: ['ja'], word: 'ja', emoji: '🔊' },
            { syl: ['je'], word: 'je', emoji: '🔊' },
            { syl: ['ji'], word: 'ji', emoji: '🔊' },
            { syl: ['jo'], word: 'jo', emoji: '🔊' },
            { syl: ['ju'], word: 'ju', emoji: '🔊' },
            { syl: ['ka'], word: 'ka', emoji: '🔊' },
            { syl: ['ke'], word: 'ke', emoji: '🔊' },
            { syl: ['ki'], word: 'ki', emoji: '🔊' },
            { syl: ['ko'], word: 'ko', emoji: '🔊' },
            { syl: ['ku'], word: 'ku', emoji: '🔊' },
            { syl: ['la'], word: 'la', emoji: '🔊' },
            { syl: ['le'], word: 'le', emoji: '🔊' },
            { syl: ['li'], word: 'li', emoji: '🔊' },
            { syl: ['lo'], word: 'lo', emoji: '🔊' },
            { syl: ['lu'], word: 'lu', emoji: '🔊' },
            { syl: ['ma'], word: 'ma', emoji: '🔊' },
            { syl: ['me'], word: 'me', emoji: '🔊' },
            { syl: ['mi'], word: 'mi', emoji: '🔊' },
            { syl: ['mo'], word: 'mo', emoji: '🔊' },
            { syl: ['mu'], word: 'mu', emoji: '🔊' },
            { syl: ['na'], word: 'na', emoji: '🔊' },
            { syl: ['ne'], word: 'ne', emoji: '🔊' },
            { syl: ['ni'], word: 'ni', emoji: '🔊' },
            { syl: ['no'], word: 'no', emoji: '🔊' },
            { syl: ['nu'], word: 'nu', emoji: '🔊' },
            { syl: ['pa'], word: 'pa', emoji: '🔊' },
            { syl: ['pe'], word: 'pe', emoji: '🔊' },
            { syl: ['pi'], word: 'pi', emoji: '🔊' },
            { syl: ['po'], word: 'po', emoji: '🔊' },
            { syl: ['pu'], word: 'pu', emoji: '🔊' },
        ]
    },
    {
        id: 'KV + KV', title: 'Rak 2 — KV + KV', color: '#3b82f6',
        words: [
            { syl: ['be', 'ca'], word: 'beca', emoji: '🛺' },
            { syl: ['ci', 'ku'], word: 'ciku', emoji: '🥔' },
            { syl: ['ja', 'ri'], word: 'jari', emoji: '👉' },
            { syl: ['ku', 'ku'], word: 'kuku', emoji: '💅' },
            { syl: ['la', 'bu'], word: 'labu', emoji: '🎃' },
            { syl: ['li', 'di'], word: 'lidi', emoji: '🪵' },
            { syl: ['ma', 'ta'], word: 'mata', emoji: '👁️' },
            { syl: ['na', 'si'], word: 'nasi', emoji: '🍚' },
            { syl: ['pa', 'ku'], word: 'paku', emoji: '📌' },
            { syl: ['ra', 'ga'], word: 'raga', emoji: '🧺' },
            { syl: ['ru', 'sa'], word: 'rusa', emoji: '🦌' },
            { syl: ['sa', 'wi'], word: 'sawi', emoji: '🥬' },
            { syl: ['su', 'du'], word: 'sudu', emoji: '🥄' },
            { syl: ['ta', 'li'], word: 'tali', emoji: '🪢' },
            { syl: ['te', 'bu'], word: 'tebu', emoji: '🎋' },
        ]
    },
    {
        id: 'V + KV', title: 'Rak 3 — V + KV', color: '#22c55e',
        words: [
            { syl: ['a', 'lu'], word: 'alu', emoji: '🔨' },
            { syl: ['a', 'pi'], word: 'api', emoji: '🔥' },
            { syl: ['i', 'bu'], word: 'ibu', emoji: '👩' },
            { syl: ['i', 'si'], word: 'isi', emoji: '🥩' },
            { syl: ['u', 'bi'], word: 'ubi', emoji: '🥔' },
            { syl: ['u', 'lu'], word: 'ulu', emoji: '⛰️' },
        ]
    },
    {
        id: 'KV + KV + KV', title: 'Rak 4 — KV + KV + KV', color: '#a855f7',
        words: [
            { syl: ['be', 'ru', 'du'], word: 'berudu', emoji: '🐸' },
            { syl: ['ke', 'la', 'di'], word: 'keladi', emoji: '🍠' },
            { syl: ['ke', 'la', 'pa'], word: 'kelapa', emoji: '🥥' },
            { syl: ['ke', 'me', 'ja'], word: 'kemeja', emoji: '👕' },
            { syl: ['ke', 're', 'ta'], word: 'kereta', emoji: '🚗' },
            { syl: ['ke', 'ru', 'si'], word: 'kerusi', emoji: '🪑' },
            { syl: ['pe', 'li', 'ta'], word: 'pelita', emoji: '🪔' },
            { syl: ['pe', 'ri', 'gi'], word: 'perigi', emoji: '🕳️' },
            { syl: ['pe', 'ta', 'ni'], word: 'petani', emoji: '👨‍🌾' },
            { syl: ['pe', 'to', 'la'], word: 'petola', emoji: '🥒' },
            { syl: ['se', 'ma', 'lu'], word: 'semalu', emoji: '🌱' },
            { syl: ['se', 'pa', 'tu'], word: 'sepatu', emoji: '👞' },
            { syl: ['to', 'ma', 'to'], word: 'tomato', emoji: '🍅' },
            { syl: ['wa', 'ni', 'ta'], word: 'wanita', emoji: '👩' },
        ]
    },
    {
        id: 'KVK', title: 'Rak 5 — KVK', color: '#f97316',
        words: [
            { syl: ['bas'], word: 'bas', emoji: '🚌' },
            { syl: ['beg'], word: 'beg', emoji: '🎒' },
            { syl: ['bot'], word: 'bot', emoji: '🚤' },
            { syl: ['cat'], word: 'cat', emoji: '🎨' },
            { syl: ['jag'], word: 'jag', emoji: '🥛' },
            { syl: ['jam'], word: 'jam', emoji: '⏰' },
            { syl: ['jem'], word: 'jem', emoji: '🍯' },
            { syl: ['jet'], word: 'jet', emoji: '✈️' },
            { syl: ['kek'], word: 'kek', emoji: '🍰' },
            { syl: ['kot'], word: 'kot', emoji: '🧥' },
            { syl: ['pam'], word: 'pam', emoji: '⛽' },
            { syl: ['pen'], word: 'pen', emoji: '🖊️' },
            { syl: ['pil'], word: 'pil', emoji: '💊' },
            { syl: ['pin'], word: 'pin', emoji: '📌' },
            { syl: ['rak'], word: 'rak', emoji: '🪜' },
            { syl: ['rim'], word: 'rim', emoji: '🛞' },
            { syl: ['ros'], word: 'ros', emoji: '🌹' },
            { syl: ['sup'], word: 'sup', emoji: '🍲' },
            { syl: ['tin'], word: 'tin', emoji: '🥫' },
            { syl: ['van'], word: 'van', emoji: '🚐' },
        ]
    },
    {
        id: 'V + KVK', title: 'Rak 6 — V + KVK', color: '#eab308',
        words: [
            { syl: ['a', 'yam'], word: 'ayam', emoji: '🐔' },
            { syl: ['e', 'nam'], word: 'enam', emoji: '6️⃣' },
            { syl: ['e', 'pal'], word: 'epal', emoji: '🍎' },
            { syl: ['i', 'kan'], word: 'ikan', emoji: '🐟' },
            { syl: ['i', 'tik'], word: 'itik', emoji: '🦆' },
            { syl: ['o', 'bor'], word: 'obor', emoji: '🔥' },
            { syl: ['o', 'ren'], word: 'oren', emoji: '🍊' },
            { syl: ['o', 'tak'], word: 'otak', emoji: '🧠' },
            { syl: ['u', 'lar'], word: 'ular', emoji: '🐍' },
            { syl: ['u', 'lat'], word: 'ulat', emoji: '🐛' },
        ]
    },
];

const HERO_SHELVES_DATA = [
    {
        id: 'KV + KVK', title: 'Rak 1 — KV + KVK', color: '#ec4899',
        words: [
            { syl: ['ba', 'kul'], word: 'bakul', emoji: '🧺' },
            { syl: ['be', 'lon'], word: 'belon', emoji: '🎈' },
            { syl: ['be', 'ruk'], word: 'beruk', emoji: '🐒' },
            { syl: ['be', 'tik'], word: 'betik', emoji: '🍈' },
            { syl: ['bo', 'tol'], word: 'botol', emoji: '🍾' },
            { syl: ['ca', 'wan'], word: 'cawan', emoji: '☕' },
            { syl: ['ce', 'rek'], word: 'cerek', emoji: '🫖' },
            { syl: ['ga', 'jah'], word: 'gajah', emoji: '🐘' },
            { syl: ['ge', 'las'], word: 'gelas', emoji: '🥛' },
            { syl: ['gi', 'tar'], word: 'gitar', emoji: '🎸' },
            { syl: ['ka', 'pak'], word: 'kapak', emoji: '🪓' },
            { syl: ['ka', 'pal'], word: 'kapal', emoji: '🚢' },
            { syl: ['ka', 'sut'], word: 'kasut', emoji: '👞' },
            { syl: ['ka', 'til'], word: 'katil', emoji: '🛏️' },
            { syl: ['ke', 'tam'], word: 'ketam', emoji: '🦀' },
            { syl: ['ki', 'cap'], word: 'kicap', emoji: '🧴' },
            { syl: ['ki', 'lat'], word: 'kilat', emoji: '⚡' },
            { syl: ['ki', 'pas'], word: 'kipas', emoji: '💨' },
            { syl: ['li', 'lin'], word: 'lilin', emoji: '🕯️' },
            { syl: ['ma', 'kan'], word: 'makan', emoji: '🍽️' },
            { syl: ['ma', 'rah'], word: 'marah', emoji: '😠' },
            { syl: ['na', 'nas'], word: 'nanas', emoji: '🍍' },
            { syl: ['pa', 'gar'], word: 'pagar', emoji: '🚧' },
            { syl: ['sa', 'bun'], word: 'sabun', emoji: '🧼' },
            { syl: ['si', 'kat'], word: 'sikat', emoji: '💇' },
            { syl: ['ta', 'yar'], word: 'tayar', emoji: '🛞' },
        ]
    },
    {
        id: 'KVK + KV', title: 'Rak 2 — KVK + KV', color: '#3b82f6',
        words: [
            { syl: ['bal', 'di'], word: 'baldi', emoji: '🪣' },
            { syl: ['ben', 'di'], word: 'bendi', emoji: '🥬' },
            { syl: ['gar', 'pu'], word: 'garpu', emoji: '🍴' },
            { syl: ['jam', 'bu'], word: 'jambu', emoji: '🍐' },
            { syl: ['kun', 'ci'], word: 'kunci', emoji: '🔑' },
            { syl: ['lam', 'pu'], word: 'lampu', emoji: '💡' },
            { syl: ['lem', 'bu'], word: 'lembu', emoji: '🐄' },
            { syl: ['pin', 'tu'], word: 'pintu', emoji: '🚪' },
        ]
    },
    {
        id: 'KVK + KVK', title: 'Rak 3 — KVK + KVK', color: '#22c55e',
        words: [
            { syl: ['bis', 'kut'], word: 'biskut', emoji: '🍪' },
            { syl: ['cer', 'min'], word: 'cermin', emoji: '🪞' },
            { syl: ['cin', 'cin'], word: 'cincin', emoji: '💍' },
            { syl: ['dok', 'tor'], word: 'doktor', emoji: '👨‍⚕️' },
            { syl: ['man', 'cis'], word: 'mancis', emoji: '🔥' },
            { syl: ['mas', 'jid'], word: 'masjid', emoji: '🕌' },
            { syl: ['ram', 'but'], word: 'rambut', emoji: '💇' },
            { syl: ['rum', 'put'], word: 'rumput', emoji: '🌿' },
            { syl: ['sam', 'pah'], word: 'sampah', emoji: '🗑️' },
            { syl: ['sam', 'pan'], word: 'sampan', emoji: '🛶' },
            { syl: ['tan', 'duk'], word: 'tanduk', emoji: '🦌' },
            { syl: ['tom', 'bol'], word: 'tombol', emoji: '🚪' },
        ]
    },
    {
        id: 'KVKK', title: 'Rak 4 — KVKK', color: '#a855f7',
        words: [
            { syl: ['bank'], word: 'bank', emoji: '🏦' },
            { syl: ['gong'], word: 'gong', emoji: '🪘' },
            { syl: ['jong'], word: 'jong', emoji: '⛵' },
            { syl: ['tong'], word: 'tong', emoji: '🛢️' },
            { syl: ['wang'], word: 'wang', emoji: '💵' },
            { syl: ['zink'], word: 'zink', emoji: '🏗️' },
        ]
    },
    {
        id: 'KV + KV + KVK', title: 'Rak 5 — KV + KV + KVK', color: '#f97316',
        words: [
            { syl: ['ba', 'si', 'kal'], word: 'basikal', emoji: '🚲' },
            { syl: ['ke', 'la', 'war'], word: 'kelawar', emoji: '🦇' },
            { syl: ['ke', 'le', 'dek'], word: 'keledek', emoji: '🍠' },
            { syl: ['ke', 'tu', 'pat'], word: 'ketupat', emoji: '🍙' },
            { syl: ['pi', 'ra', 'mid'], word: 'piramid', emoji: '🔺' },
            { syl: ['pu', 'la', 'san'], word: 'pulasan', emoji: '🌰' },
            { syl: ['te', 'le', 'fon'], word: 'telefon', emoji: '☎️' },
            { syl: ['te', 'ti', 'kus'], word: 'tetikus', emoji: '🖱️' },
            { syl: ['zi', 'ra', 'fah'], word: 'zirafah', emoji: '🦒' },
        ]
    },
    {
        id: 'KVK + KV + KVK', title: 'Rak 6 — KVK + KV + KVK', color: '#eab308',
        words: [
            { syl: ['cem', 'pe', 'dak'], word: 'cempedak', emoji: '🍈' },
            { syl: ['cen', 'da', 'wan'], word: 'cendawan', emoji: '🍄' },
            { syl: ['jam', 'ba', 'tan'], word: 'jambatan', emoji: '🌉' },
            { syl: ['kom', 'pu', 'ter'], word: 'komputer', emoji: '💻' },
            { syl: ['pem', 'ba', 'ris'], word: 'pembaris', emoji: '📏' },
            { syl: ['tem', 'pa', 'yan'], word: 'tempayan', emoji: '🏺' },
        ]
    },
];
